name: Bug report
description: Signaler un problème avec Blur Auto Clicker
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Merci du signalement. Remplissez ce que vous pouvez — toute information est précieuse. Des captures d'écrans sont appréciées.

  - type: checkboxes
    id: checks
    attributes:
      label: Checked
      options:
        - label: J'ai vérifié qu'il n'y a pas de tickets identitiques
          required: true

  - type: input
    id: version
    attributes:
      label: Version Blur Auto Clicker
      placeholder: "Exemple: 3.5.0"
    validations:
      required: true

  - type: textarea
    id: settings
    attributes:
      label: Quels paramètres utilisiez vous ?
      placeholder: |
        Mode simple, click gauche, on/off, 50 CPS
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Comment reproduire le bug
      placeholder: |
        1. Ouvrir l'app
        2. Activer le mode avancé 
        3. Mettre 100 CPS
        4. Commencer le programme
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Qu'est ce qui est censé se passer ?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Qu'est ce qui s'est passé ?
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Quelque chose d'autre ?
      description: Capture d'écran, logs, version Windows, enregistrement — tout peut aider.
