name: Suggérer une amélioration
description: Suggérer une idée pour Blur Auto Clicker
title: "[Feature]: "
labels:
  Amélioration
body:
  - type: markdown
    attributes:
      value: |
        Merci pour la suggéstion. Que voulez vous et pourquoi ?

  - type: checkboxes
    id: checks
    attributes:
      label: Coché
      options:
        - label: J'ai vérifié qu'il n'y a pas eu de requête similaire précédemment
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Que manque t'il ou qu'est ce qui ne vous convient pas ?
      placeholder: Je veux pouvoir ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Comment voulez vous que ça fonctionne ?
      placeholder: Ce serait bien si Blur Auto Clicker pouvait ...
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Quel domaine ?
      options:
        - UI / UX
        - Programme de click
        - Raccourcis clavier
        - Superposition
        - Paramètres / Stockage
        - Installeur / Mise a jour
        - Autre
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Autre chose ?
      description: Maquette, régérence, capture d'écran, hacks que vos avez essayé ...
